---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2/geotype/point/lon/{{
  longitude }}/lat/{{ latitude }}/data.json
polling_headers: ''
custom_fields:
- keyname: city
  field_type: string
  placeholder: Stockholm
  name: City
- keyname: longitude
  field_type: string
  placeholder: '18.5'
  name: Longitude
- keyname: latitude
  field_type: string
  placeholder: '59.4'
  name: Latitude
- keyname: items_narrow
  field_type: select
  name: Items to show on half width
  options:
  - 1
  - 2
  - 3
  - 4
- keyname: items_wide
  field_type: select
  name: Items to show on full width
  options:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
name: SMHI
refresh_interval: 720
